# Generated by Django 3.2.6 on 2021-09-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('uphone', models.CharField(max_length=20)),
                ('ucompany', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=200)),
                ('usubject', models.CharField(max_length=100)),
                ('umessage', models.TextField()),
                ('udatetime', models.DateTimeField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
