# Generated by Django 3.2.6 on 2021-09-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytable',
            name='udatetime',
            field=models.CharField(max_length=20),
        ),
    ]
