# Generated by Django 3.2.6 on 2021-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_alter_entrytable_udatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrytable',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
