# Generated by Django 3.2.6 on 2021-09-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0003_entrytable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrytable',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='entrytable',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
